# Generated by Django 2.2.1 on 2019-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190523_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Actors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Country',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Genre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Language',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Plot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Writer',
            field=models.TextField(blank=True),
        ),
    ]
