# Generated by Django 2.2.1 on 2019-05-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190523_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Type',
        ),
    ]
