# Generated by Django 2.2.1 on 2019-05-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='BoxOffice',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='DVD',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Production',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Response',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Website',
        ),
    ]
