# Generated by Django 2.2.1 on 2019-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190523_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='BoxOffice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='DVD',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Production',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Website',
            field=models.TextField(blank=True),
        ),
    ]
