# Generated by Django 2.2.1 on 2019-05-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
