# Generated by Django 2.2.1 on 2019-05-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190523_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.TextField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='Actors',
            field=models.ManyToManyField(blank=True, to='movies.Actor'),
        ),
    ]
