# Generated by Django 2.2.1 on 2019-05-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20190523_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_name',
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
