# Generated by Django 2.2.1 on 2019-05-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190523_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Actors',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Actor'),
        ),
    ]
