# Generated by Django 2.2.1 on 2019-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20190523_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Actors',
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
