# Generated by Django 2.2.1 on 2019-05-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20190523_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Actors',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
