# Generated by Django 2.2.1 on 2019-05-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
    ]
