# Generated by Django 2.2.1 on 2019-05-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_comment_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
