# Generated by Django 2.2.1 on 2019-05-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Total_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Actors',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Awards',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='BoxOffice',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Country',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='DVD',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Director',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Genre',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Language',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Metascore',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Plot',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Production',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Rated',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Released',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Response',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Runtime',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Title',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Type',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Website',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Writer',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Year',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbID',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbRating',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbVotes',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
